name: CI

on:
  push:
  repository_dispatch:
    types: [trigger-ci-workflow]

env:
  FORCE_COLOR: true
  NODE_VERSION: 18

jobs:
  build:
    name: Build SPA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.action != 'repository_dispatch' }}

      - uses: actions/checkout@v3
        if: ${{ github.event.action == 'repository_dispatch' }}
        with:
          ref: ${{ github.event.client_payload.sha }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --prefer-offline --pure-lockfile

      - name: Run Linter
        run: yarn lint

      - name: Build SPA
        run: yarn build

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy SPA
        if: success() && ${{ github.ref == 'refs/heads/master' }}
        uses: wopian/netlify-actions-colors-fix/cli@1e378c943b20b381c815ca478fef65fe3a30937a
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod --message='Deployed ${{ github.sha }} via GitHub Actions'
