name: CI

on:
  push:

env:
  FORCE_COLOR: true
  NODE_VERSION: 20

jobs:
  setup:
    name: Lint & Deploy SPA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Linter
        run: yarn lint

      - name: Update Submodules
        if: success() && github.ref == 'refs/heads/develop'
        run: git submodule update --init --remote

      - name: Build and Typecheck SPA
        run: yarn build

      - name: Create Release
        if: success() && github.ref == 'refs/heads/develop'
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy SPA
        if: success() && github.ref == 'refs/heads/develop'
        run: yarn dlx -p @netlify/framework-info -p netlify-cli netlify deploy --dir=dist --prod --message='Deployed ${{ github.sha }} via GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
